version: "3"

services:
  postgresdb:
    image: postgres:11
    ports:
      - "5433:5432"
    restart: always
    networks:
      - bnet
    environment:
      POSTGRES_PASSWORD: root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - bnet
    env_file: .env

networks:
  bnet:
    driver: bridge
